# setting
## window
### 설치해야할 프로그램
  - [R](https://www.r-project.org/)
  - [Rstudio](https://www.rstudio.com/)
  - [git](https://git-scm.com/)
  - [Zotero](https://www.zotero.org/)
  - [miniconda](https://docs.conda.io/en/latest/miniconda.html)

### Rtools설치
- window에서 R사용시 rtools4가 필요
- [Rtools](https://cran.rstudio.com/bin/windows/Rtools/)

### window 영어 설정
- [슬기로운통계생활 - 유투브](https://www.youtube.com/watch?v=7UZL0j3QpUo&t=1s)
- 설정-언어
- windows display language: English
- preferred languages
  - English - Korean
- Administrative language settings - Language for non-Unicode programs = Korean
- Regional Format = Korean

### locale encoding의 이해
- Locale(로케일): OS별 국가마다 제공하는 여러 표현방식
    - LC_COLLATE(문자정렬), LC_CTYPE(문자처리), LC_MESSAGES(언어/문화 등)
- locale 관련 함수
    - Sys.getlocale(): 현재 설정된 로케일을 확인
    - Sys.setlocale(category='LC_ALL', locale='locale name'): 로케일 설정을 변경
        - category 인자에는 'LC_COLLATE', 'LC_CTYPE', 'LC_MONETARY', 'LC_TIME' 등 개별 카테고리를 지정할 수 있으나 편의상 이 모든걸 통틀은 'LC_ALL'을 사용하여 지정
        - locale 인자에 지정할 locale name은 운영체제에 따라 서로 다름
        - Sys.setlocale() 함수 안에 아무런 인자를 넣지 않으면 운영체제의 default로 설정
    - localeToCharset(): 현재 설정된 한글 인코딩 방식을 확인
- 예시시
    - 문자열 깨질 때 로케일 설정 - 윈도우 
```
Sys.getlocale() 
localeToCharset() 
```
    - 미국 로케일로 로케일을 변환하기 
```
Sys.setlocale(category = 'LC_ALL',locale = 'english') 
localeToCharset() 
```
    - 우리나라로 로케일 변경하기 
```
Sys.setlocale(category = 'LC_ALL',locale='korean') 
localeToCharset()
```

### miniconda 설치 및 가상환경 생성
- [슬기로운통계생활 - 유투브](https://www.youtube.com/watch?v=DFN__fmPvmI&t=937s)
- google: git and install miniconda 검색
- 설치과정에 'Select the first option for “Add Anaconda to my PATH environment variable” and also leave the selection on “Register Anaconda as my default Python 3.7”. Click on “Install”.' 체크
- cmd: conda
```
conda --version
conda update --all
```

- 가상환경
```
conda env list
conda create -n 'nm'
conda create -n 'nm' python=3.6
codna env remove -n 'nm'
conda list
conda activate 'nm'
conda deactivate
conda install 'package_nm'
```

### R에서 Python 사용하기
- [슬기로운통계생활 - 유투브](https://www.youtube.com/watch?v=krDkfOCLsA4)
- reticulate package 설치
```
install.packages('reticulate')
```
- miniconda에 설치된 가상환경 연결 및 확인
```
reticulate::use_condaenv("url")
reticulate::py_config()
reticulate::py_discover_config()
```
- 가상환경 주소 확인
    - cmd 내 가상환경 activate
    - conda list
        - package가 설치된 환경 주소 나옴


### git 연결 오류(port 22)
- 윈도우에서 git 설정한 후 Rstudio와 연결시 오류 발생
```
ssh: connect to host github.com port 22: Operation timed out
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.
```
- 이유는 방화벽이나 ISP가 설정한 방화벽이 port22에서 ssh연결을 차단하는 경우 [출처](https://velog.io/@resident000/ssh-%EC%A0%91%EC%86%8D-%EC%8B%9C-port-22-blocked-%EB%AC%B8%EC%A0%9C)
- 해결방법은 \~/ssh/config에 아래 내용을 추가
```
Host github.com
Hostname ssh.github.com
Port 443
```
- 이때, config파일이 없을 경우 만들어야함
    - 파워쉘이나 CMD에서 vim 명령어는 먹히지 않음
- Git Bash를 실행해 config 생성 [출처](https://dev-coco.tistory.com/107)
    - 마우스 오른쪽 클릭 Git Bash Here
    - 디렉토리 생성(mkdir)
```
mkdir ~/.ssh
```
    - config 파일 생성
```
vim ~/.ssh/config
```
    - config 아래 호스트 정보 등록
      - i를 눌러 입력하고 esc
      - :wq 명령어로 저장 및 종료

### rmarkdown - pdf 및 한글사용을 위한 설정
- tinytex 설치 [슬기로운통계생활 - 유투브](https://www.youtube.com/watch?v=WMzUq9PyNIQ&t=996s)
```
install.packages("tinytex")
tinytex::install_tinytex()
```

- 아래 순서와 같이 진행
    - use_tinytex()를 실행 한 후 tlmgr파일이 있는 tinytex 폴더로 경로 설정
    - tlmgr의 위치: User/name/AppData/Roaming/ (tlmgr 한번 실행할 것)
```
tinytex::use_tinytex()
tinytex::tinytex_root()
```
- yml에 다음 내용 추가
```
output: pdf_document
header-includes:
    - \usepacakge{kotex}
```
- [KTUG한글TEX사용자그룹](http://www.ktug.org/xe/)-내려받기-Microsoft Windows용 설치방법
    - TeXLive windows에 설치하기의 4. ko.TeXLive 설정
    - 아래 내용 cmd에서 실행 
```
> tlmgr repository add https://cran.asia/KTUG/texlive/tlnet ktug
> tlmgr pinning add ktug *
> tlmgr install ktugbin
> tlmgr install texworks-config
> tlmgr install nanumttf hcr-lvt
```

### Visual Studio code 테마 설정
- 설치방법 [슬기로운통계생활 - 유투브](https://www.youtube.com/watch?v=oXBTqqBOa_k)
- google: rstudio vscode theme
  - [rscodeio](https://github.com/anthonynorth/rscodeio)
```
install.packages("remotes")
remotes::install_github("anthonynorth/rscodeio")
rscodeio::install_theme()
```

### 네이버 - D2=Coding
- [D2 coding 글꼴](https://github.com/naver/d2codingfont)


### font 설정
- extrafont의 여러 문제로 showtext pacakge로 변경
- 참고자료
    - [showtext: Using Fonts More Easily in R Graphs](https://cran.rstudio.com/web/packages/showtext/vignettes/introduction.html)
    - [너의 폰트를 써라! (R에서도)](https://danbi-ncsoft.github.io/etc/2018/07/24/use-your-font-in-r.html)
- TTF(일반문서에 적합) 뿐만 아니라 OTF(그래픽 디자인 출력에 적합)도 설치 가능
- 단점: Rstudio 실행마다 폰트 설치를 실행해야함
- KoPub 서체 설치
- fonts 위치
    - C:/Windows/fonts
- **font_paths()**: 폰트가 설치된 경로
- **font_files()**: 윈도우에 설치된 폰트의 path, file, family, face, version, ps_name에 대한 파일 데이터
- **font_add**: 폰트 설치(family 내 bold, italic, bolditalic, symbol 설정 가능)
```
font_add(family = "Arial",
         regular = "C:/Windows/Fonts/arial.ttf",
         bold = "C:/Windows/Fonts/arialbd.ttf",
         italic = "C:/Windows/Fonts/ariali.ttf",
         bolditalic = "C:/Windows/Fonts/arialbi.ttf",
         symbol = NULL)
font_add(family = "KoPubDotumL",
         regular = "C:/Windows/Fonts/KoPubWorld Dotum_Pro Light.otf")
font_add(family = "KoPubDotumM",
         regular = "C:/Windows/Fonts/KoPubWorld Dotum_Pro Medium.otf")
font_add(family = "KoPubDotumB",
         regular = "C:/Windows/Fonts/KoPubWorld Dotum_Pro Bold.otf")
```
- **showtext_auto()**:  turn on/off the automatic use of showtext functionality
- **font_families()**: 설치된 폰트확인

```{r showtext example, message=FALSE, warning=FALSE}
ggplot(NULL, aes(x = 1, y = 1)) + 
ylim(0.8, 1.3) + 
annotate("text", 1, 1.2, family = 'Arial', size = 15, fontface = 'italic',
         label = 'Arial italic') +
annotate("text", 1, 1.1,family = 'KoPubDotumL', size = 15,
         label = "KoPubWorldDotum_Pro Light") + 
annotate("text", 1, 1, family = 'KoPubWorldDotum_Pro Medium', size = 15,
         label = "KoPub Dotum M") + 
annotate("text", 1, 0.9, family = 'KoPubDotumB', size = 15,
         label = "KoPubWorldDotum_Pro Bold") +
theme_void()
```

### font에 대한 snippet 설정
- [슬기로운 통계생활 - 유투브](https://www.youtube.com/watch?v=hgoiJQ2Rc1Q&list=PLKtLBdGREmMlsQvFyWWRsg7OX6S3kfuJk&index=14)
- Options-code-Editing에서 Snippets 설정
    - edit snippets
- snippet 아래 코드는 항상 tab을 누르고 사용
    - ${1:'nm'}은 snippet입력 후 곧바로 입력되는 위치를 의미하며, tab과 shift+tab을 이용해 이동 가능

```
snippet kfonts
	library(showtext)
	font_add(family = "KoPubDotumL",
	         regular = "C:/Windows/Fonts/KoPubWorld Dotum_Pro Light.otf")
	font_families()
	showtext_auto()
```
```
snippet libset
	lib <- c(${1:"lib1"},${2:"lib2"},${3:"lib3"})
	lapply(lib, library, character.only = T)
	rm(lib)
```

- 코드창에서는 snippet이 잘 되지만 markdown에서는 잘 안됨
    - Tools-Modify Keyboard Shortcuts...-snippet 검색 - inser snippet에 대한 shortcut을 'shift+Space'로 설정

### 사용하기 좋은 package
- *datapasta*
    - Excel에서 바로 붙여넣을 수 있음(tibble, vector,...)
    - addins












