# R tips
## Affinity Designer for SVGLITE
Affiinity Designer 사용을 위한 svglite package의 code 수정방법에 대해 알아본다.

Affiinity Designer는 Adobe사의 Illustrator와 같은 벡터드로잉프로그램이다. Serif는 Affiinity 프로그램에 대해 1회 구매시 특정 버전 이하에 대해서는 기간에 관계 없이 이용할 수 있도록 하여 Adobe 제품과 비교해 더 경제적인 장점이 있다. 필자는 R에서 ggplot2를 이용해 작성된 그래프를 수정하기 위해 이 프로그램을 사용하고 있다.

ggplot2에서는 svg 등 벡터 이미지파일을 내보내기 위해 svglite package를 사용한다. 그러나 Affiinity Designer는 svglite로 내보내진 벡터이미지파일을 정확하게 읽지 못한다. Angelo Limeta는 이 문제의 원인을 기술하고, 해결하는 [방법](https://github.com/angelolimeta/svgliteForAffinity)을 제안했다. 그러나 Angelo Limeta는 svglite 1.2.2에 한정해 문제를 해결해, 2021년 기준 2.0.0버전인 svglite에서는 문제를 해결할 수 없다. 이 페이지에서는 최신 버전의 svglite에서 어떻게 문제를 해결하는지 기술한다.

### code 수정

svglite는 multiple CSS style과 CDATA sections 다루지 못한다. ggplot2는 svglite의 svglite함수를 이용하는데, 이 함수는 C++로 구성된 'devSVG.cpp'를 이용한다. 따라서 'devSVG.cpp' 내 code를 일부 코드를 수정해 문제를 해결한다.

CRAN에 등록된 svglite 가운데 package sources 'svglite 2.0.0.tar.gz'를 다운받고, 압축을 해제하면, src파일에 'devSVG.cpp'파일이 있다. windows binaries 또는 mac os binaries를 통해 설치된 파일에서는 code를 수정 할 수 없다.

아래 a의 //Setting default styles의 code를, b의 //Setting default styles로 바꾼후 저장한다. 이때, devSVG.cpp 파일은 메모장을 이용해 읽을 수 있다.

a code
```
...
// Setting default styles
  (*stream) << "<defs>\n";
  (*stream) << "  <style type='text/css'><![CDATA[\n";
  (*stream) << "    line, polyline, path, rect, circle {\n";
  (*stream) << "      fill: none;\n";
  (*stream) << "      stroke: #000000;\n";
  (*stream) << "      stroke-linecap: round;\n";
  (*stream) << "      stroke-linejoin: round;\n";
  (*stream) << "      stroke-miterlimit: 10.00;\n";
  (*stream) << "    }\n";
  (*stream) << "  ]]></style>\n";
  (*stream) << "</defs>\n";
...
  (*stream) << "<rect width='100%' height='100%'";
```

b code
```
...
// Setting default styles
  (*stream) << "<defs>\n";
  (*stream) << "  <style>\n";
  (*stream) << "    line {\n";
  (*stream) << "      fill: none;\n";
  (*stream) << "      stroke: #000000;\n";
  (*stream) << "      stroke-linecap: round;\n";
  (*stream) << "      stroke-linejoin: round;\n";
  (*stream) << "      stroke-miterlimit: 10.00;\n";
  (*stream) << "    }\n";
  (*stream) << "    polyline {\n";
  (*stream) << "      fill: none;\n";
  (*stream) << "      stroke: #000000;\n";
  (*stream) << "      stroke-linecap: round;\n";
  (*stream) << "      stroke-linejoin: round;\n";
  (*stream) << "      stroke-miterlimit: 10.00;\n";
  (*stream) << "    }\n";
  (*stream) << "    path {\n";
  (*stream) << "      fill: none;\n";
  (*stream) << "      stroke: #000000;\n";
  (*stream) << "      stroke-linecap: round;\n";
  (*stream) << "      stroke-linejoin: round;\n";
  (*stream) << "      stroke-miterlimit: 10.00;\n";
  (*stream) << "    }\n";
  (*stream) << "    rect {\n";
  (*stream) << "      fill: none;\n";
  (*stream) << "      stroke: #000000;\n";
  (*stream) << "      stroke-linecap: round;\n";
  (*stream) << "      stroke-linejoin: round;\n";
  (*stream) << "      stroke-miterlimit: 10.00;\n";
  (*stream) << "    }\n";
  (*stream) << "    circle {\n";
  (*stream) << "      fill: none;\n";
  (*stream) << "      stroke: #000000;\n";
  (*stream) << "      stroke-linecap: round;\n";
  (*stream) << "      stroke-linejoin: round;\n";
  (*stream) << "      stroke-miterlimit: 10.00;\n";
  (*stream) << "    }\n";
  (*stream) << "  </style>\n";
  (*stream) << "</defs>\n";
...
```

### 발생문제
(window) tar.gz 파일로 압축하는 방법  
반디집을 사용하였다. 먼저 반디집 내 새로압축 기능 가운데 압축형식을 tar로 설정하고 압축한다. 그 다음 tar로 압축된 파일을 다시 압충형식 gz로 설정하고 압축한다. 두 단계를 거쳐, tar.gz 파일로 압축 할 수 있다.

(window) 수동 설치가 되지 않는 문제  
tar.gz파일로 된 패키지가 R에서 수동으로 설치되지 않는 문제가 있다. 관련 내용은 [블로그](<https://blog.naver.com/PostView.nhn?blogId=itisik&logNo=221597983934&parentCategoryNo=&categoryNo=&viewDate=&isShowPopularPosts=false&from=postView>) 를 참고하였다.

설치가 되지 않는 원인은 CRAN 내 ripa package가 내려갔기 때문이다. ripa는 CRAN 내 [아카이브](https://cran.r-project.org/src/contrib/Archive/ripa/)에서 설치 할 수 있다. 그리고 ripa 설치를 위해선, Rtools가 설치되어야 한다.

(mac) m1칩을 사용하는 경우
(mac) homebrew 설치 및 libpng package 설치했음
