# data preprocessing

## DBI & RSQLite
RAM보다 큰 대용량데이터를 다루기 위해 DBI와 RSQLite 패키지를 사용한다. RSQLite는 R에서 SQLite DB를 사용할 수 있도록 하며, SQLite는 데이터베이스 전체를 파일 하나에 저장하기 때문에 백업과 이동이 간편하다. 참고한 웹페이지는 다음과 같다.
- [R에서 DB사용(Sqlite)](https://unfinishedgod.netlify.app/2020/07/24/r%EC%97%90%EC%84%9C-db-%EC%82%AC%EC%9A%A9sqlite/)

단, 전체 DB를 가지고 데이터 전처리를 진행하지 않는걸 추천한다. 일부 sample을 가지고 데이터 전처리를 수행한 후, 한 파일로 합치는 용도로 쓴다. 이때, DB에 대한 데이터 집계처리는 필요한 테이블을 추출하는 용도로만 사용한다. 예를 들어, case_when 등 function은 dbplyr로 잘 처리가 되지 않으며 오래걸린다. 특히, 메모리 문제로 오류가 발생할 가능성이 있다. 파일명과 경로는 한글이 아닌 영어를 되도록 사용하자!

### DB생성
- DB의 생성은 다음과 같이 진행한다.
    - **dbConnect()**함수를 활용해 연결한다. SQLite()는 드라이버의 이름을 의미한다.

```
dbConnect(SQLite(), dbname = 'dbname')
```
    - **dbSendQuery**를 사용하여 DB의 틀을 작성한다.
```
dbSendQuery(con,
            "CREATE TABLE E_db (
              year TEXT,
              sido TEXT,
              gender TEXT,
              start_yr TEXT,
              start_mn TEXT)")
```
    - **dbListTables(con)**로 테이블리스트를 확인한다.
    - **dbGetQuery(con, "SELECT * FROM E_db")**

- DB에 데이터를 다음과 같이 저장한다.
    - **dbWriteTable(con, name = "E_db", value = db_3, row.names = F, append = T)**
        - value는 저장할 데이터를 의미한다.
        - append=T일 경우 데이터를 아래로 붙인다.
        - **dbDisconnect(con)**시 자동으로 저장된다.
        
## SQLite

- vscode로 넘어가며 sqlite를 직접 사용한다. 참고 자료는 다음과 같다.
    - [SQL문법](https://ssabum.github.io/p/sql%EB%AC%B8%EB%B2%95/) 주로 이 자료 활용
    - [프로그램 개발 지식 공유](https://araikuma.tistory.com/category/SQLite)
    - [SQLite-DB생성과 변경](https://inuplace.tistory.com/421?category=911622)
    - [HeyTech-SQLite](https://heytech.tistory.com/category/Big%20Data/SQLite)
    - [Command Line Shell For SQLite](https://www.sqlite.org/cli.html) 공식문서
    - [디비랑](https://dbrang.tistory.com/)

### SQL 개념
- SQL(Structured Query Language)는 관계형 데이터베이스 관리시스템(RDMBS)의 데이터를 관리하기 위해 설계된 특수 목적의 프로그래밍 언어
- SQL문법의 세가지 종류

DDL(데이터 정의 언어)| DML(데이터 조작 언어)|DCL(데이터 제어 언어)
--------|--------|-------------------------|--------------------------
CREATE | INSERT |GRANT
DROP | UPDATE | REVOKE
ALTER | DELETE | COMMIT
RENAME | SELECT | ROLLBACK

### DB 생성
- 새파일 만들기
        - DB: name.db
        - 스크립트: name.sql
- .으로 시작하는 명령어는 sqlite3 프로그램의 기능을 실행하는 명령어로 SQL문법에 속하지 않음

```
CREATE DATABASE [DB이름]
SHOW TABLES
DROP DATABASE [DB이름]
```

### 테이블 다루기
- 데이터 타입의 유형
        - NULL. The value is a NULL value.
        - INTEGER. The value is a signed integer, stored in 0, 1, 2, 3, 4, 6, or 8 bytes depending on the magnitude of the value.
        - REAL. The value is a floating point value, stored as an 8-byte IEEE floating point number.
        - TEXT. The value is a text string, stored using the database encoding (UTF-8, UTF-16BE or UTF-16LE).
        - BLOB. The value is a blob of data, stored exactly as it was input.

- 테이블 생성
        - 테이블 생성시 자료형 뒤에 UNIQUE / NOT NULL / DEFAULT 0 등의 옵션을 주어 제약
        - CHAR vs VARCHAR : CHAR는 자료형의 크기가 고정적이고, VARCHAR는 가변적
        - AUTO_INCREMENT PRIMARY KEY 옵션을 주면 1씩 자동적으로 증가하는 정수 값을 넣어준다. (ID 부여 등에 활용)
```
CREATE dbname table (
  column1 datatype PRIMARY KEY,
  column2 datatype default = "value",
  ...
);
```

- 테이블 조회
        - `.TABLES`: 테이블 목록 조회
        - `.schema table`: 특정 테이블 스키마 조회

- 테이블 제거
```
DROP TABLE table;
```

- 컬럼 관련 주요 명령어
        - ADD COLUMN에 대하여 defalut 값 가능
```
ALTER TABLE [테이블이름] ADD COLUMN [칼럼 이름 및 자료형] --추가
ALTER TABLE [테이블이름] DROP COLUMN [칼럼 이름] --삭제
ALTER TABLE [테이블이름] MODIFY (컬럼명1 데이터 유형 [DEFAULT 식] [NOT NULL],...) --수정
ALTER TABLE [테이블이름] RENAME TO [변경 이름] --이름변경
CREATE TABLE [새 테이블 이름] AS SELECT [가져올 COL] FROM [가져올 테이블] --테이블 생성 from 테이블
```

```
ALTER TABLE Y2010 ADD COLUMN V1_year TEXT DEFAULT "2010";
ALTER TABLE Y2010 ADD COLUMN V8_ksic_C TEXT DEFAULT "C9";
```


- 조회(select)
        - options: LIMIT(원하는 개수 가져오기), OFFSET(특정 위치에서 가져오기), WHERE(조건을 통해 값 가져오기), DISTINCT(중복없이 가져오기)
        - *은 모든 컬럼을 의미
```
SELECT * FROM table;
SELECT * FROM table LIMIT 100;
```

- 삭제(DELETE)
        - 특정 조건에 맞는 row 제거
```
DELETE FROM table
WHERE condition;
```

- 수정(UPDATE)

```
UPDATE table
SET column1=value1, column2=value2, ...
WHERE condition;
```

### 외부 데이터 입력하기
- csv파일: 첫번째 행을 column의 name으로 인식해 저장
        - table 명이 db에 있을 경우 binding하고 없을 경우 새로 생성
- options(공식문서 참조)
        - `--csv`, `--ascii`
        - `--skip n`
        - `--schema temp`: option may be used to specify that the table is in some other schema. (다른 테이블의 스키마를 이용)

```
.import --csv 경로포함외부파일.csv table
```

- .separator = ","로 미리 지정해 부를수도 있음
```
.separator = ","
.import 경로포함외부파일.csv table
```

### 외부 데이터 출력하기
- 출력 옵션은 ascii, column, csv, html, insert, line, quote, tabs(텍스트형식), tcl 중 하나. 엑셀 안됨
```
.mode csv
.output filenm
sqlite>select * from table;
sqlite>.quit
```

### 테이블 가공
- GROUP BY: 그룹화할 기준
        - count, avg, max, min, sum

```
SELECT V29_emp_T, sum(*), count(*) FROM Y2010_re
GROUP BY V29_emp_T;
```

```
SELECT V9_ksic_1D, sum(V30_emp_M), sum(V30_emp_M_r) FROM TEST3;
```

- LIKE (문자열 다루기)
- _(언더스코어)와 %(퍼센트)기호로 동작, 두 개를 조합해서도 사용 가능
        - **_**: 반드시 이 자리에 한 개의 문자가 존재해야 한다는 뜻
        - **%**: 이 자리에 문자열이 있을 수도, 없을 수도 있다. 0개 이상이라는 뜻

```
-- 20대인 사람들만 가져올 때 --
  
SELECT *
FROM users
WHERE age LIKE '2_';

-- 지역번호가 02인 사람만 가져올 때 --
  
SELECT *
FROM users
WHERE phone LIKE '02-%';

-- 핸드폰 중간 번호가 반드시 4자리면서 511로 시작되는 사람들 --
  
SELECT * FROM users
WHERE phone LIKE '%-511_-%';
```

- 정렬(ORDER BY)
        - ASC 또는 DESC
```
-- ASC: 오름차순 / DESC: 내림차순 --
SELECT columns FROM table
ORDER BY column1, column2 ASC | DESC;
```


### 조건절
- CASE WHEN
```
UPDATE Y2010 SET V29_emp_T = CASE
             WHEN V29_emp_T == "*" THEN 0
             WHEN V29_emp_T == "**" THEN 0
             WHEN V29_emp_T == "***" THEN 0
             WHEN V29_emp_T == "****" THEN 0
             WHEN V29_emp_T == "*****" THEN 0
             ELSE V29_emp_T
             END;
```
- END 다음 새로운 변수명 입력
```
CREATE TABLE TEST4 AS SELECT *,
       CASE WHEN V30_emp_M == "*" THEN 0
            WHEN V30_emp_M == "**" THEN 0
            WHEN V30_emp_M == "***" THEN 0
            WHEN V30_emp_M == "****" THEN 0
            WHEN V30_emp_M == "*****" THEN 0
            ELSE V30_emp_M
            END V30_emp_M_r
FROM TEST;
```

### 관계설정
- 'FOREIGN KEY' 을 사용하여 테이블 사이 관계를 설정한다.
- 관계를 이룰 테이블의 FOREIGN KEY COL을 테이블의 COL 중 하나로 정한다.
- FOREIGN KEY(대상 테이블의 FOREIGN KEY가 되어줄 COL) REFERENCES 대상 테이블(FOREIGN KEY가 되어줄 COL)
- ex. FOREIGN KEY(FranchiseeID) REFERENCES Franchisee(FranchiseeID)
관계가 설정된 테이블은 먼저 삭제될 수 없다. (관계를 만든 테이블을 먼저 삭제해야 한다.)

```
FOREIGN KEY(대상 테이블의 FOREIGN KEY가 되어줄 COL) REFERENCES 대상 테이블(FOREIGN KEY가 되어줄 COL)
```

### 자주사용하는 Operators
- [Operators, and Parse-Affecting Attributes](https://www.sqlite.org/lang_expr.html)
- Equals can be either = or ==.
- The non-equals operator can be either != or <>. 
- The || operator is "concatenate" - it joins together the two strings of its operands.

### 자주 사용하는 명령어
- `VACUMM`: DB의 용량 정리